### ISSUE TITLE
Why is iwinfo not used

### ISSUE THREAD

**Issue by Emilv2** [fbradyirl/openwrt-luci-rpc#29]
### Description
Why is the iwinfo not used for connected devices? I see it is in the code, but commented out. For some devices (Iphone X in my case) the current method does not work, they stay in the list although they are not connected anymore.

### What I Did
Currently I use a custom component in homeassistant: https://github.com/rds76/home-assistant/blob/master/custom_components/device_tracker/luci_ap.py , but I don't see why this more reliable method should not be used in the official component.

**Comment by fbradyirl** [comment]
iwinfo is not used because that presumes you are using OpenWRT as a wifi access point, which I am not. 

My module works when OpenWRT is used only as a DHCP server. 

There are other modules for using the wifi as a tracker as you mention.

**Comment by Emilv2** [comment]
Would you be willing to accept patches so we can use this? It would be nice to have this in the official Home Assistant luci component. I would think using OpenWRT also as a wifi access point instead of only as a DCHP server is the more common case.
