### ISSUE TITLE
openwrt-luci-rpc use old rpc call when VERSION_ID is 'snapshot'

### ISSUE THREAD

**Issue by ntcong** [fbradyirl/openwrt-luci-rpc#30]
When openwrt's version is snapshot, openwrt-luci-rpc default to use rpc_sys_arp_call which is not available.

It should default to rpc_ip_call or try to use both.

**Comment by mwxp06** [comment]
Hi @fbradyirl 
Any progress about this?

Problem with wrong verions is part of this issue:
https://github.com/home-assistant/core/issues/25779

**Comment by fbradyirl** [comment]
May I suggest you fork and maintain this codebase going forward as I no longer use this component in HA so have no means to test and support changes.
